generatorName: r
outputDir: samples/client/petstore/R
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/r
httpUserAgent: PetstoreAgent
prependFormOrBodyParameters: true
sortParamsByRequiredFlag: false
additionalProperties:
  packageName: petstore
